name: Actions Setup Workflow
on:
  push:
    ignore_branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v5
      - name: Configurar El Node v22
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
