name: Contexto de Github Actions
on:
  push

jobs:
  setup:
    runs-on: ubuntu-24.04
    env:
      RAILS_ENV: test #Variable de entorno para el entorno de Rails
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v5
      - name: Mostrar información del commit
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Disparado por: ${{ github.actor }}"
          echo "Entorno: ${{ env.RAILS_ENV }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Referencia: ${{ github.ref_name }}"