name: Deploy a producción
on:
  push:
    braches_ignore:
      - main
    # branches:
    #   - main
    paths: #Si no hubo cambios en estos archivos, no se ejecutará el evento push
      - "app/**"
      - "config/**"
      - "Gemfile"
      - "Gemfile.lock"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Desplegar
        run: echo "Desplegando a mi aplicación de producción"