name: Hola Mundo
on:
  push: {}
  pull_request: {}

jobs:
  saludar:
    runs-on: ubuntu-24.04
    steps:
      - name: Decir Hola
        run: echo "Hola Desde GitHub Actions! ${{ github.ref_name }} 25/07/2026"
      - name: Mostrar información del sistema
        run: cat /etc/os-release
      - name: Mostrar la información del usuario
        run: whoami
        # exit run: whoami