name: Info del token
on:
  push:
    branches-ignore:
      - main

jobs:
  consultar-token:
    runs-on: ubuntu-24.04
    steps:
      - name: Consultar el repositorio con la API de GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}  --jq '.full_name, .visibility'